Feat. Convert integration tests code to node module
neutron-org/neutronjsplus pull request #1
Opened 2023-07-26 21:50 UTC by albertandrejev

This PR will transforms code from neutron integration tests into node js package

2023-08-10 08:50 UTC, swelf19 reviewed
It would be nice to have README file with a list of env variables and default values (the same as in tests actually).

2023-08-11 14:19 UTC, NeverHappened approved these changes

2023-08-14 12:31 UTC, sotnikov-s requested changes

2023-08-16 10:04 UTC, albertandrejev commented on src/helpers/tge.ts
> +    throw new Error('res should be truthy');
Unfortunately this lays out of scope of this PR. Please create JIRA task to refactor this behavior.

2023-08-17 09:27 UTC, albertandrejev commented
> It would be nice to have README file with a list of env variables and default values (the same as in tests actually).

env variables is related to integration tests only. But I added README anyway.

2023-08-17 10:05 UTC, sotnikov-s approved these changes

2023-09-11 09:56 UTC, pr0n00gler approved these changes

2023-09-12 07:12 UTC, sotnikov-s submitted a review, later dismissed

2023-09-12 09:18 UTC, pr0n00gler approved these changes

2023-09-12 09:28 UTC, merged