feat: update neutronjs to sdk47
neutron-org/neutronjsplus pull request #11
Opened 2023-11-23 10:08 UTC by NeverHappened

TODO

2023-11-29 11:54 UTC, pr0n00gler reviewed
What's the reason of moving files from `src/helpers` folder into `src`?

2023-11-29 11:54 UTC, pr0n00gler commented on src/common_localcosmosnet.ts
> +          cosmosclient.rest.tx.BroadcastTxMode.Async,
Why not `Sync` mode?

2023-11-29 11:54 UTC, pr0n00gler commented on src/common_localcosmosnet.ts
> +        console.log(e);
Redundant log?

2023-11-29 12:32 UTC, NeverHappened commented
https://github.com/neutron-org/neutronjsplus/pull/11#pullrequestreview-1755071868
reason is that it's redundant directory, since all the library code was in "helpers".
I think it's the old legacy of the code being in neutron-integration-tests, where it made sense.
So I think in the future (refactoring) we can move files under some meaningful structure, but `helpers` is not it.

2023-11-29 15:51 UTC, NeverHappened commented on src/common_localcosmosnet.ts
> +          cosmosclient.rest.tx.BroadcastTxMode.Async,
Guess no reason, will change to Sync

2023-12-01 09:48 UTC, NeverHappened commented
https://github.com/neutron-org/neutron-tests/actions/runs/7046159446

2023-12-04 17:42 UTC, pr0n00gler approved these changes

2023-12-05 09:13 UTC, swelf19 approved these changes

2023-12-05 10:06 UTC, pr0n00gler requested changes
Please add info into Readme how to generate protobuf

2023-12-05 10:06 UTC, pr0n00gler commented on gen-proto.sh
> +git clone git@github.com:skip-mev/block-sdk.git $REPOS/block-sdk --branch v1.1.0 --depth 1
We don't have block-sdk now

2023-12-06 15:43 UTC, sotnikov-s commented on package.json
> +  "version": "0.1.0-rc4",
I think we should have a mapping neutron version <-> neutronjsplus version somewhere, for example in the repo readme. let's add it? at least starting with this version: neutron v2.0.0 <-> neutronjsplus 0.1.0

2023-12-08 10:09 UTC, pr0n00gler commented on gen-proto.sh
> +git clone git@github.com:skip-mev/block-sdk.git $REPOS/block-sdk --branch v1.1.0 --depth 1
Decided to leave, since we'll include block-sdk in a month anyway

2023-12-08 10:10 UTC, pr0n00gler submitted a review, later dismissed

2023-12-08 11:36 UTC, merged