feat: add dex bindings
neutron-org/neutronjsplus pull request #24
Opened 2024-02-16 10:09 UTC by swelf19

2024-02-16 13:02 UTC, NeverHappened requested changes

2024-02-16 13:02 UTC, NeverHappened commented on src/dex_bindings.ts
> +  lower_tick1: PoolReserves;
is it upper_tick1?

2024-02-20 12:16 UTC, NeverHappened commented on src/dex_bindings.ts
> +  ipper_tick_index: number; // i64
typo?

2024-02-22 18:30 UTC, pr0n00gler approved these changes

2024-02-23 08:13 UTC, NeverHappened submitted a review, later dismissed

2024-02-23 10:16 UTC, NeverHappened approved these changes

2024-03-20 08:58 UTC, pr0n00gler approved these changes

2024-03-20 08:58 UTC, merged